"""V2.1.0 本地闭环：按日期排餐、点单分配、购买量与入库。"""
import os
from pathlib import Path
from playwright.sync_api import expect, sync_playwright

ROOT = Path(__file__).resolve().parents[1]
with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=True, executable_path=str(ROOT / '.android-tools/playwright/chromium-1223/chrome-win64/chrome.exe'))
    page = browser.new_page(viewport={'width': 390, 'height': 844})
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto(os.environ.get('E2E_URL', 'http://127.0.0.1:5173'), wait_until='networkidle')
    page.get_by_role('navigation', name='主导航').wait_for()
    def state():
        return page.evaluate('JSON.parse(localStorage.getItem("shiguang-v1"))')
    def nav(name):
        page.get_by_role('navigation', name='主导航').get_by_role('button', name=name, exact=True).click()

    recipe = state()['recipes'][0]
    page.get_by_role('button', name='添加' + recipe['name'], exact=True).click()
    page.get_by_role('button', name='确认选菜', exact=False).click()
    expect(page.get_by_role('dialog', name='我的点单清单')).to_contain_text(recipe['name'])
    page.get_by_role('button', name='确认并同步', exact=False).click()
    page.wait_for_function('JSON.parse(localStorage.getItem("shiguang-v1")).pendingOrders.length===1')
    assert state()['pendingOrders'][0]['recipeSnapshot']['name'] == recipe['name']

    nav('周菜单')
    page.get_by_role('tab', name='当日菜单').click()
    expect(page.get_by_role('button', name='待分配 1 道')).to_be_visible()
    page.get_by_role('button', name='待分配 1 道').click()
    page.get_by_label('为' + recipe['name'] + '选择餐次').select_option('中')
    page.wait_for_function('JSON.parse(localStorage.getItem("shiguang-v1")).pendingOrders.length===0')
    page.wait_for_function('JSON.parse(localStorage.getItem("shiguang-v1")).pendingOrders.length===0')
    expect(page.get_by_role('region', name='午餐')).to_contain_text(recipe['name'])
    assert not page.get_by_role('region', name='夜宵').count()
    nav('点单')
    page.get_by_role('button', name='添加' + recipe['name'], exact=True).click()
    page.get_by_role('button', name='确认选菜', exact=False).click()
    page.get_by_role('button', name='确认并同步', exact=False).click()
    page.wait_for_function('JSON.parse(localStorage.getItem("shiguang-v1")).pendingOrders.length===1')
    nav('周菜单')
    page.get_by_role('button', name='待分配 1 道').click()
    page.get_by_label('为' + recipe['name'] + '选择餐次').select_option('中')
    page.wait_for_function('JSON.parse(localStorage.getItem("shiguang-v1")).pendingOrders.length===0')
    expect(page.get_by_role('region', name='午餐').locator('.today-dish')).to_have_count(1)
    expect(page.get_by_role('region', name='午餐')).to_contain_text('×2')
    page.get_by_role('region', name='午餐').locator('.today-dish-name').click()
    snapshot = page.locator('.meal-snapshot-dialog')
    expect(snapshot).to_contain_text('制作步骤')
    timer = snapshot.locator('.recipe-timer')
    timer.get_by_role('button', name='计时').click()
    timer.locator('.recipe-timer-time').click()
    timer.get_by_role('spinbutton', name='分钟').fill('1')
    timer.get_by_role('spinbutton', name='秒').fill('30')
    timer.get_by_role('button', name='确定').click()
    expect(timer.locator('output')).to_have_text('01:30')
    timer.get_by_role('button', name='开始计时').click()
    timer.get_by_role('button', name='重置').click()
    expect(timer.locator('output')).to_have_text('01:30')
    snapshot.get_by_label('关闭弹窗').click()
    page.get_by_role('tab', name='周菜单').click()
    page.get_by_role('button', name='一周总览').click()
    expect(page.locator('.meal-table-row')).to_have_count(35)
    page.get_by_role('tab', name='当日菜单').click()
    page.get_by_role('tab', name='周菜单').click()
    expect(page.get_by_role('button', name='返回单日')).to_be_visible()
    page.locator('.week-picker > summary').click()
    page.get_by_role('button', name='下一周').click()
    page.locator('.week-picker > summary').click()
    page.locator('.meal-table-row').first.click()
    week_recipe = state()['recipes'][1]
    page.get_by_role('dialog', name='早餐 · 管理菜品').get_by_role('button', name=week_recipe['name']).click()
    page.get_by_role('dialog', name='早餐 · 管理菜品').get_by_label('关闭弹窗').click()
    assert any(item['name'] == week_recipe['name'] for plan in state()['weeks'].values() for items in plan.values() for item in items)

    nav('菜篮子')
    page.get_by_role('button', name='全部排单').click()
    expect(page.locator('.shopping-card')).not_to_have_count(0)
    card = page.locator('.shopping-card').first
    item_name = card.locator('h3').inner_text().split('›')[0].strip()
    card.get_by_role('button', name='查看' + item_name + '日期来源').click()
    expect(page.get_by_role('dialog', name=item_name)).to_contain_text(recipe['name'])
    page.get_by_role('dialog', name=item_name).get_by_label('关闭弹窗').click()
    card.get_by_role('button', name='修改' + item_name + '实际购买量').click()
    edit = page.get_by_role('dialog', name='修改' + item_name + '购买量')
    edit.get_by_role('spinbutton').fill('500')
    edit.get_by_role('button', name='保存购买量').click()
    card.get_by_role('checkbox').check()
    page.wait_for_function('Object.values(JSON.parse(localStorage.getItem("shiguang-v1")).purchaseDrafts).some(x=>x.checked)')
    nav('点单')
    page.get_by_role('button', name='添加' + recipe['name'], exact=True).click()
    page.get_by_role('button', name='确认选菜', exact=False).click()
    page.get_by_role('button', name='确认并同步', exact=False).click()
    page.wait_for_function('JSON.parse(localStorage.getItem("shiguang-v1")).pendingOrders.length===1')
    nav('菜篮子')
    page.get_by_role('button', name='已买待入库 1 项 · 确认入库').click()
    stock_dialog=page.get_by_role('dialog', name='核对已买食材并入库')
    expect(stock_dialog.get_by_role('button', name='需求已变化，复核后确认此数量')).to_be_visible()
    stock_dialog.get_by_role('button', name='确认入库 · 1 项').click()
    expect(stock_dialog).to_be_visible()
    stock_dialog.get_by_role('button', name='需求已变化，复核后确认此数量').click()
    page.evaluate("Object.defineProperty(localStorage,'setItem',{configurable:true,value:()=>{throw Error('test write failure')}})")
    page.get_by_role('dialog', name='核对已买食材并入库').get_by_role('button', name='确认入库 · 1 项').click()
    expect(page.get_by_role('dialog', name='核对已买食材并入库')).to_be_visible()
    assert not any(item['name'] == item_name and item['qty'] == 500 for item in state()['fridge'])
    page.evaluate('delete localStorage.setItem')
    page.get_by_role('dialog', name='核对已买食材并入库').get_by_role('button', name='确认入库 · 1 项').click()
    page.wait_for_function('JSON.parse(localStorage.getItem("shiguang-v1")).fridge.some(x=>x.qty===500)')
    assert any(item['name'] == item_name and item['qty'] == 500 for item in state()['fridge'])
    assert not any(draft.get('checked') for draft in state()['purchaseDrafts'].values())
    page.reload(wait_until='networkidle')
    nav('周菜单')
    page.get_by_role('tab', name='当日菜单').click()
    expect(page.get_by_role('region', name='午餐')).to_contain_text(recipe['name'])
    page.wait_for_function("Array.from(document.querySelectorAll('[role=status]')).some(el => el.textContent.includes('已保存'))")
    page.evaluate('''recipe => {
      const data=JSON.parse(localStorage.getItem('shiguang-v1'));
      data.weeks={};data.pendingOrders=[];data.purchaseDrafts={};data.confirmedRecipes=[recipe];data.confirmed={[recipe.id]:1};
      data.fridge=recipe.ingredients.map((item,index)=>({id:'legacy-stock-'+index,name:item.name,qty:10000,unit:item.unit,date:new Date().toLocaleDateString('sv-SE'),days:0}));
      localStorage.setItem('shiguang-v1',JSON.stringify(data));
    }''', recipe)
    page.reload(wait_until='networkidle')
    nav('菜篮子')
    expect(page.locator('.basket-legacy')).to_contain_text('旧版待安排菜品')
    expect(page.locator('.basket-legacy')).to_contain_text('当前食材已备齐')
    page.locator('.basket-legacy summary').click()
    page.locator('.basket-legacy').get_by_role('button', name='归入指定日期').click()
    page.wait_for_function('JSON.parse(localStorage.getItem("shiguang-v1")).pendingOrders.length===1')
    assert state()['confirmed'] == {}
    nav('点单')
    page.get_by_role('button', name='添加' + recipe['name'], exact=True).click()
    page.get_by_role('button', name='确认选菜', exact=False).click()
    page.get_by_role('button', name='确认并同步', exact=False).click()
    page.wait_for_function('JSON.parse(localStorage.getItem("shiguang-v1")).pendingOrders.length===2')
    nav('周菜单')
    page.get_by_role('tab', name='当日菜单').click()
    page.get_by_role('button', name='待分配 2 道').click()
    page.get_by_label('为' + recipe['name'] + '选择餐次').first.select_option('早')
    page.get_by_label('为' + recipe['name'] + '选择餐次').select_option('早')
    page.wait_for_function('JSON.parse(localStorage.getItem("shiguang-v1")).pendingOrders.length===0')
    expect(page.get_by_role('region', name='早餐').locator('.today-dish')).to_have_count(1)
    expect(page.get_by_role('region', name='早餐')).to_contain_text('×2')
    assert not errors, errors
    browser.close()

print('PASS V2.1.0: 点单、当日分配、整周视图、采购量、入库与重启')
