import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {getPreference,setPreference,setSecret} from '../storage.js';
import {backup} from '../services.js';
import {defaultDAV,inspectSync,downloadVersion,uploadVersion,recordDownload} from '../sync.js';
export default function SyncPanel({state,onRestore}) {
 const [config,setConfig]=useState(defaultDAV);const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [context,setContext]=useState(null);const [last,setLast]=useState('尚未同步');
 useEffect(()=>{getPreference('dav-config',defaultDAV).then(setConfig);getPreference('sync-base').then(v=>v&&setLast(v.time));},[]);
 async function apply(ctx,direction,version){setBusy(true);try{if(direction==='upload'){await uploadVersion(ctx,state);}else{const incoming=await downloadVersion(ctx,version);await setPreference('before-restore',backup(state));await onRestore({...incoming,qty:state.qty,recipeDraft:state.recipeDraft});await recordDownload(version||ctx.remote,incoming);}setLast(new Date().toISOString());setContext(null);toast.success('同步完成');}catch(e){toast.error(e.message);}finally{setBusy(false);}}
 async function inspect(){setBusy(true);try{const ctx=await inspectSync(config,state);if(ctx.action==='equal')toast.success('本地与云端一致');else setContext(ctx);}catch(e){toast.error(e.message);}finally{setBusy(false);}}
 return <section><h3>坚果云手动同步</h3><p>最近同步：{last}。只在点击后联网，不会自动覆盖冲突数据。</p><label>WebDAV 根地址<input value={config.url} onChange={e=>setConfig({...config,url:e.target.value})}/></label><label>账号<input value={config.username} onChange={e=>setConfig({...config,username:e.target.value})}/></label><label>应用密码<input type="password" autoComplete="new-password" value={password} placeholder="留空保留已保存密码" onChange={e=>setPassword(e.target.value)}/></label><div className="actions"><button className="outline" onClick={async()=>{try{await setPreference('dav-config',config);if(password)await setSecret('dav',password);setPassword('');toast.success('同步配置已保存');}catch(e){toast.error(e.message);}}}>保存同步配置</button><button className="primary" disabled={busy} onClick={inspect}>{busy?'正在处理…':'检查并同步'}</button></div>
 {context&&<div className="notice"><div><strong>{context.action==='choose'?'本地与云端需要选择版本':'请确认同步方向'}</strong><p>本地：{state.recipes.length} 道菜，{state.fridge.length} 条库存。云端：{context.remote?`${context.remote.time}，设备 ${context.remote.device}，${context.remote.recipes??'?'} 道菜`:'尚无数据'}。</p><p>下载会先保留本地备份；上传会保留已有云端版本。冲突按整份数据选择。</p><div className="actions">{context.action!=='download'&&<button className="primary" disabled={busy} onClick={()=>apply(context,'upload')}>保留本地并上传</button>}{context.remote&&context.action!=='upload'&&<button className="outline" disabled={busy} onClick={()=>apply(context,'download')}>采用云端版本</button>}<button className="outline" onClick={()=>setContext(null)}>暂不处理</button></div>{context.remote?.versions?.length>0&&<details><summary>最近云端备份</summary>{context.remote.versions.map(v=><p key={v.id}>{v.time}<button className="text-link" disabled={busy} onClick={()=>{if(window.confirm('用这个备份整体替换本地数据？会先保留本地备份。'))apply(context,'download',v);}}>恢复此版本</button></p>)}</details>}</div></div>}
 </section>;
}
